version: '3'

services:
  mongo:
    image: mongo
    container_name: dev_mogno
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: dev_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo